<?php

namespace skeeks\cms\mcp\services;

use skeeks\cms\shop\models\ShopBill;
use skeeks\cms\shop\models\ShopBillItem;
use skeeks\cms\shop\models\ShopDocument;
use skeeks\cms\shop\models\ShopDocumentItem;
use yii\base\Exception;
use yii\db\Expression;

class ShopDocumentService extends AbstractCmsService
{
    public function documentList(array $a): array { $q = ShopDocument::find(); if (method_exists($q, 'forManager')) { $q->forManager(\Yii::$app->user->identity); } $this->applyFilters($q, ShopDocument::class, $a, ['cms_company_id', 'cms_user_id', 'type', 'status']); $this->applySearch($q, ShopDocument::class, $a, ['number', 'description', 'comment']); $this->applyDateRange($q, ShopDocument::class, $a, 'issued_at'); return $this->page($q->orderBy(['id' => SORT_DESC]), $a, [$this, 'documentData']); }
    public function documentGet(array $a): array { return $this->documentData($this->findAllowed(ShopDocument::class, $a), true); }
    public function documentCreate(array $a): array { $m = new ShopDocument(); $m->loadDefaultValues(); return $this->mutate($m, $a); }
    public function documentUpdate(array $a): array { return $this->mutate($this->findAllowed(ShopDocument::class, $a), $a); }
    public function documentStats(array $a): array { $groups = ['company' => 'cms_company_id', 'type' => 'type', 'status' => 'status']; $g = $a['group_by'] ?? 'type'; if (!isset($groups[$g])) { throw new Exception('Unsupported document group_by.'); } $q = ShopDocument::find(); if (method_exists($q, 'forManager')) { $q->forManager(\Yii::$app->user->identity); } $this->applyDateRange($q, ShopDocument::class, $a, 'issued_at'); $f = ShopDocument::tableName().'.'.$groups[$g]; return ['group_by' => $g, 'items' => $q->select(['group_value' => $f, 'count' => new Expression('COUNT(*)'), 'amount' => new Expression('SUM(amount)')])->groupBy($f)->asArray()->all()]; }
    public function itemList(array $a): array { $allowed=ShopDocument::find()->select('id');if(method_exists($allowed,'forManager')){$allowed->forManager(\Yii::$app->user->identity);}$q=ShopDocumentItem::find()->andWhere(['shop_document_id'=>$allowed]);$this->applyFilters($q,ShopDocumentItem::class,$a,['shop_document_id','shop_product_id','source_shop_bill_id','source_shop_bill_item_id','currency_code']);$this->applySearch($q,ShopDocumentItem::class,$a,['name','discount_name']);return $this->page($q->orderBy(['shop_document_id'=>SORT_DESC,'sort'=>SORT_ASC,'id'=>SORT_ASC]),$a,[$this,'itemData']); }
    public function itemGet(array $a): array { $m=$this->find(ShopDocumentItem::class,$a);$this->assertDocumentAllowed($m->shop_document_id);return $this->itemData($m,true); }
    public function itemCreate(array $a): array { return \Yii::$app->db->transaction(function()use($a){$source=array_merge($a,(array)($a['attributes']??[]));$document=$this->assertDocumentAllowed((int)($source['shop_document_id']??0));$this->assertEditable($document);$m=new ShopDocumentItem();$m->loadDefaultValues();$this->applyWritable($m,$a,array_diff($this->itemWritable(),['shop_document_id']));$m->shop_document_id=$document->id;$this->assertDocumentSourcesAllowed($m);$this->save($m,'Document item validation failed');$this->recalculateDocument($document);return $this->itemData($m,true);}); }
    public function itemUpdate(array $a): array { return \Yii::$app->db->transaction(function()use($a){$m=$this->find(ShopDocumentItem::class,$a);$document=$this->assertDocumentAllowed($m->shop_document_id);$this->assertEditable($document);$this->applyWritable($m,$a,array_diff($this->itemWritable(),['shop_document_id']));$this->assertDocumentSourcesAllowed($m);$this->save($m,'Document item validation failed');$this->recalculateDocument($document);return $this->itemData($m,true);}); }
    public function documentData(ShopDocument $m, bool $details = false): array { return $this->withRelations($m, $details ? ['company', 'cmsUser', 'createdBy', 'sellerContractor', 'buyerContractor', 'bills', 'deals', 'documentItems'] : [], ['url' => function ($x) { return $x->url; }, 'pdf_url' => function ($x) { return $x->pdfUrl; },'type_text'=>function($x){return $x->typeAsText;},'status_text'=>function($x){return $x->statusAsText;}]); }
    protected function mutate(ShopDocument $m, array $a): array { $isNew=$m->isNewRecord;$this->applyWritable($m, $a, $m->safeAttributes());if(array_key_exists('items',$a)){if(!$isNew){throw new Exception('Use shop_document_item_create/update for an existing document.');}$m->documentItemsData=(array)$a['items'];}return $this->documentData($this->save($m, 'Document validation failed'), true); }
    protected function itemWritable(): array { return ['shop_document_id','shop_product_id','source_shop_bill_id','source_shop_bill_item_id','name','measure_name','quantity','price','discount_amount','discount_value','discount_name','currency_code','vat_name','extra_data','sort']; }
    protected function assertDocumentAllowed(int $id): ShopDocument { return $this->findAllowed(ShopDocument::class,['id'=>$id]); }
    protected function assertDocumentSourcesAllowed(ShopDocumentItem $item): void { if($item->source_shop_bill_id){$this->findAllowed(ShopBill::class,['id'=>$item->source_shop_bill_id]);}if($item->source_shop_bill_item_id){$source=$this->find(ShopBillItem::class,['id'=>$item->source_shop_bill_item_id]);$this->findAllowed(ShopBill::class,['id'=>$source->shop_bill_id]);if($item->source_shop_bill_id&&(int)$source->shop_bill_id!==(int)$item->source_shop_bill_id){throw new Exception('source_shop_bill_item_id does not belong to source_shop_bill_id.');}} }
    protected function assertEditable(ShopDocument $m): void { if(!$m->isEditable){throw new Exception('Document items are immutable in the current status.');} }
    protected function recalculateDocument(ShopDocument $m): void { $m->amount=(float)$m->getDocumentItems()->sum('amount');$m->discount_amount=(float)$m->getDocumentItems()->sum('discount_amount');$this->save($m,'Document total recalculation failed'); }
    public function itemData(ShopDocumentItem $m,bool $details=false): array { $d=$this->recordData($m);$d['amount_without_discount']=$m->amountWithoutDiscount;if($details){$d['product']=$m->shopProduct?$this->recordData($m->shopProduct):null;$d['source_bill']=$m->sourceShopBill?$this->recordData($m->sourceShopBill):null;$d['source_bill_item']=$m->sourceShopBillItem?$this->recordData($m->sourceShopBillItem):null;}return $d; }
}
