<?php

namespace skeeks\cms\mcp\services;

use skeeks\cms\shop\models\ShopBill;
use skeeks\cms\shop\models\ShopBillItem;
use yii\base\Exception;
use yii\db\Expression;

class ShopBillService extends AbstractCmsService
{
    public function billList(array $a): array { $q = ShopBill::find()->forManager(\Yii::$app->user->identity); $this->applyFilters($q, ShopBill::class, $a, ['cms_company_id', 'cms_user_id', 'paid_at', 'closed_at', 'currency_code']); $this->applySearch($q, ShopBill::class, $a, ['code', 'description', 'company_name']); $this->applyDateRange($q, ShopBill::class, $a, 'due_at'); foreach ((array)($a['named_filters'] ?? []) as $name) { if ($name === 'unpaid' || $name === 'overdue') { $this->unpaid($q, $name === 'overdue'); } else { throw new Exception('Unknown bill named filter: '.$name); } } return $this->page($q->orderBy(['id' => SORT_DESC]), $a, [$this, 'billData']); }
    public function billGet(array $a): array { return $this->billData($this->findAllowed(ShopBill::class, $a), true); }
    public function billCreate(array $a): array { $m = new ShopBill(); $m->loadDefaultValues(); return $this->mutate($m, $a); }
    public function billUpdate(array $a): array { return $this->mutate($this->findAllowed(ShopBill::class, $a), $a); }
    public function billStats(array $a): array { $groups = ['company' => 'cms_company_id', 'user' => 'cms_user_id', 'currency' => 'currency_code', 'paid' => 'paid_at']; $metrics = ['count' => 'COUNT(*)', 'amount' => 'SUM(amount)']; $g = $a['group_by'] ?? 'company'; $m = $a['metric'] ?? 'count'; if (!isset($groups[$g], $metrics[$m])) { throw new Exception('Unsupported bill statistics slice.'); } $q = ShopBill::find()->forManager(\Yii::$app->user->identity); $this->applyFilters($q, ShopBill::class, $a, ['cms_company_id', 'cms_user_id', 'currency_code']); $this->applyDateRange($q, ShopBill::class, $a, 'created_at'); foreach ((array)($a['named_filters'] ?? []) as $name) { if (!in_array($name, ['unpaid', 'overdue'], true)) { throw new Exception('Unknown bill named filter: '.$name); } $this->unpaid($q, $name === 'overdue'); } $f = ShopBill::tableName().'.'.$groups[$g]; return ['group_by' => $g, 'metric' => $m, 'items' => $q->select(['group_value' => $f, 'value' => new Expression($metrics[$m])])->groupBy($f)->asArray()->all()]; }
    public function itemList(array $a): array { $allowed=ShopBill::find()->forManager(\Yii::$app->user->identity)->select('id');$q=ShopBillItem::find()->andWhere(['shop_bill_id'=>$allowed]);$this->applyFilters($q,ShopBillItem::class,$a,['shop_bill_id','shop_product_id','currency_code']);$this->applySearch($q,ShopBillItem::class,$a,['name','discount_name']);return $this->page($q->orderBy(['shop_bill_id'=>SORT_DESC,'sort'=>SORT_ASC,'id'=>SORT_ASC]),$a,[$this,'itemData']); }
    public function itemGet(array $a): array { $m=$this->find(ShopBillItem::class,$a);$this->assertBillAllowed($m->shop_bill_id);return $this->itemData($m,true); }
    public function itemCreate(array $a): array { return \Yii::$app->db->transaction(function()use($a){$source=array_merge($a,(array)($a['attributes']??[]));$bill=$this->assertBillAllowed((int)($source['shop_bill_id']??0));$this->assertEditable($bill);$m=new ShopBillItem();$m->loadDefaultValues();$this->applyWritable($m,$a,array_diff($this->itemWritable(),['shop_bill_id']));$m->shop_bill_id=$bill->id;$this->save($m,'Bill item validation failed');$this->recalculateBill($bill);return $this->itemData($m,true);}); }
    public function itemUpdate(array $a): array { return \Yii::$app->db->transaction(function()use($a){$m=$this->find(ShopBillItem::class,$a);$bill=$this->assertBillAllowed($m->shop_bill_id);$this->assertEditable($bill);$this->applyWritable($m,$a,array_diff($this->itemWritable(),['shop_bill_id']));$this->save($m,'Bill item validation failed');$this->recalculateBill($bill);return $this->itemData($m,true);}); }
    public function billData(ShopBill $m, bool $details = false): array { return $this->withRelations($m, $details ? ['company', 'cmsUser', 'senderContractor', 'receiverContractor', 'payments', 'documents', 'deals', 'billItems'] : [], ['url' => function ($x) { return $x->url; }, 'pay_url' => function ($x) { return $x->payUrl; }, 'documented_amount'=>function($x){return $x->documentedAmount;},'document_balance_amount'=>function($x){return $x->documentBalanceAmount;},'is_closed_by_documents'=>function($x){return $x->isClosedByDocuments;}]); }
    protected function mutate(ShopBill $m, array $a): array { $isNew=$m->isNewRecord;$this->applyWritable($m, $a, $m->safeAttributes());if(array_key_exists('items',$a)){if(!$isNew){throw new Exception('Use shop_bill_item_create/update for an existing bill.');}$m->billItemsData=(array)$a['items'];}return $this->billData($this->save($m, 'Bill validation failed'), true); }
    protected function itemWritable(): array { return ['shop_bill_id','shop_product_id','name','measure_name','quantity','price','discount_amount','discount_value','discount_name','currency_code','vat_name','sort']; }
    protected function assertBillAllowed(int $id): ShopBill { return $this->findAllowed(ShopBill::class,['id'=>$id]); }
    protected function assertEditable(ShopBill $m): void { if($m->paid_at||$m->closed_at){throw new Exception('Paid or closed bill items are immutable.');} }
    protected function recalculateBill(ShopBill $m): void { $m->amount=(float)$m->getBillItems()->sum('amount');$m->discount_amount=(float)$m->getBillItems()->sum('discount_amount');$this->save($m,'Bill total recalculation failed'); }
    public function itemData(ShopBillItem $m,bool $details=false): array { $d=$this->recordData($m);$d['amount_without_discount']=$m->amountWithoutDiscount;$d['documented_quantity']=$m->documentedQuantity;$d['documented_amount']=$m->documentedAmount;$d['document_balance_quantity']=$m->documentBalanceQuantity;$d['document_balance_amount']=$m->documentBalanceAmount;$d['is_closed_by_documents']=$m->isClosedByDocuments;if($details){$d['product']=$m->shopProduct?$this->recordData($m->shopProduct):null;}return $d; }
    protected function unpaid($q, bool $overdue): void { $t = ShopBill::tableName(); $q->andWhere(['or', [$t.'.paid_at' => null], [$t.'.paid_at' => 0]])->andWhere(['or', [$t.'.closed_at' => null], [$t.'.closed_at' => 0]]); if ($overdue) { $q->andWhere(['<', $t.'.due_at', time()]); } }
}
