<?php

namespace skeeks\cms\mcp\services;

use skeeks\cms\shop\models\ShopStoreDocMove;
use skeeks\cms\shop\models\ShopStoreProduct;
use skeeks\cms\shop\models\ShopStoreProductMove;
use yii\base\Exception;
use yii\db\Expression;

class ShopStoreMovementService extends AbstractCmsService
{
    public function documentList(array $a): array { $q=ShopStoreDocMove::find();$this->applyFilters($q,ShopStoreDocMove::class,$a,['doc_type','shop_store_id','shop_order_id','client_cms_user_id','is_active']);$this->applySearch($q,ShopStoreDocMove::class,$a,['comment']);$this->applyDateRange($q,ShopStoreDocMove::class,$a,'created_at');return $this->page($q->orderBy(['id'=>SORT_DESC]),$a,[$this,'documentData']); }
    public function documentGet(array $a): array { return $this->documentData($this->find(ShopStoreDocMove::class,$a),true); }
    public function documentUpdate(array $a): array { $m=$this->find(ShopStoreDocMove::class,$a);if($m->is_active){throw new Exception('Approved movement document is immutable.');}$source=array_merge($a,(array)($a['attributes']??[]));if($m->getShopStoreProductMoves()->exists()&&(array_key_exists('doc_type',$source)||array_key_exists('shop_store_id',$source))){throw new Exception('doc_type and shop_store_id cannot be changed after movement rows are added.');}$this->applyWritable($m,$a,['doc_type','shop_store_id','shop_order_id','client_cms_user_id','comment']);return $this->documentData($this->save($m,'Movement document validation failed'),true); }
    public function documentCreateFull(array $a): array
    {
        if(empty($a['items'])){throw new Exception('items are required.');}
        $doc=new ShopStoreDocMove();$doc->loadDefaultValues();$this->applyWritable($doc,$a,['doc_type','shop_store_id','shop_order_id','client_cms_user_id','comment']);$doc->is_active=0;
        $t=ShopStoreDocMove::getDb()->beginTransaction();
        try{$this->save($doc,'Movement document validation failed');foreach((array)$a['items'] as $row){$position=ShopStoreProduct::findOne((int)($row['shop_store_product_id']??0));if(!$position||$position->shop_store_id!=$doc->shop_store_id){throw new Exception('shop_store_product not found in selected shop_store.');}$quantity=(float)($row['quantity']??0);if(!$quantity){throw new Exception('Movement quantity must not be zero.');}if(in_array($doc->doc_type,[ShopStoreDocMove::DOCTYPE_SALE,ShopStoreDocMove::DOCTYPE_WRITEOFF],true)){$quantity=-abs($quantity);}elseif(in_array($doc->doc_type,[ShopStoreDocMove::DOCTYPE_RETURN,ShopStoreDocMove::DOCTYPE_POSTING],true)){$quantity=abs($quantity);}$move=new ShopStoreProductMove();$move->loadDefaultValues();$move->shop_store_doc_move_id=$doc->id;$move->shop_store_product_id=$position->id;$move->product_name=(string)($row['product_name']??$position->productName);$move->quantity=$quantity;$move->price=(float)($row['price']??$position->selling_price);$move->is_active=0;$this->save($move,'Store product movement validation failed');}if(!empty($a['approve'])){$this->approve($doc,true);} $t->commit();}catch(\Throwable $e){$t->rollBack();throw $e;}return $this->documentData($doc,true);
    }
    public function documentApprove(array $a): array { $doc=$this->find(ShopStoreDocMove::class,$a);$t=ShopStoreDocMove::getDb()->beginTransaction();try{$this->approve($doc,(bool)($a['is_active']??true));$t->commit();}catch(\Throwable $e){$t->rollBack();throw $e;}return $this->documentData($doc,true); }
    public function movementList(array $a): array { $q=ShopStoreProductMove::find()->joinWith('shopStoreDocMove doc');$this->applyFilters($q,ShopStoreProductMove::class,$a,['shop_store_doc_move_id','shop_store_product_id','is_active']);if(isset($a['shop_store_id'])){$q->andWhere(['doc.shop_store_id'=>$a['shop_store_id']]);}$this->applySearch($q,ShopStoreProductMove::class,$a,['product_name']);return $this->page($q->orderBy([ShopStoreProductMove::tableName().'.id'=>SORT_DESC]),$a); }
    public function movementGet(array $a): array { return $this->recordData($this->find(ShopStoreProductMove::class,$a)); }
    public function movementCreate(array $a): array { $doc=ShopStoreDocMove::findOne((int)($a['shop_store_doc_move_id']??0));if(!$doc){throw new Exception('shop_store_doc_move not found.');}$m=new ShopStoreProductMove();$m->loadDefaultValues();$this->applyMovement($m,$doc,$a,true);return $this->recordData($this->save($m,'Store product movement validation failed')); }
    public function movementUpdate(array $a): array { $m=$this->find(ShopStoreProductMove::class,$a);$doc=$m->shopStoreDocMove;$this->applyMovement($m,$doc,$a,false);return $this->recordData($this->save($m,'Store product movement validation failed')); }
    public function documentStats(array $a): array { $q=ShopStoreProductMove::find()->joinWith('shopStoreDocMove doc')->andWhere([ShopStoreProductMove::tableName().'.is_active'=>1]);if(!empty($a['date_from'])){$q->andWhere(['>=','doc.created_at',$this->timestamp($a['date_from'])]);}if(!empty($a['date_to'])){$q->andWhere(['<=','doc.created_at',$this->timestamp($a['date_to'],true)]);}$group=$a['group_by']??'store';$fields=['store'=>'doc.shop_store_id','type'=>'doc.doc_type','product'=>ShopStoreProductMove::tableName().'.shop_store_product_id'];if(!isset($fields[$group])){throw new Exception('Unsupported movement statistics slice.');}$field=$fields[$group];return ['group_by'=>$group,'items'=>$q->select(['group_value'=>$field,'quantity'=>new Expression('SUM('.ShopStoreProductMove::tableName().'.quantity)'),'value'=>new Expression('SUM('.ShopStoreProductMove::tableName().'.quantity * '.ShopStoreProductMove::tableName().'.price)')])->groupBy($field)->asArray()->all()]; }

    protected function approve(ShopStoreDocMove $doc,bool $active): void { foreach($doc->shopStoreProductMoves as $move){$move->is_active=$active?1:0;$this->save($move,'Movement approval failed');$position=$move->shopStoreProduct;if($position){$sum=$position->getShopStoreProductMoves()->andWhere(['is_active'=>1])->sum('quantity');$position->quantity=(float)$sum;$position->isAllowCorrection=false;$this->save($position,'Store quantity recalculation failed');}}$doc->is_active=$active?1:0;$this->save($doc,'Movement document approval failed'); }
    protected function applyMovement(ShopStoreProductMove $m,ShopStoreDocMove $doc,array $a,bool $new): void { if($doc->is_active){throw new Exception('Approved movement document is immutable.');}$source=array_merge($a,(array)($a['attributes']??[]));$position=ShopStoreProduct::findOne((int)($source['shop_store_product_id']??$m->shop_store_product_id));if(!$position||$position->shop_store_id!=$doc->shop_store_id){throw new Exception('shop_store_product not found in selected shop_store.');}$quantity=(float)($source['quantity']??$m->quantity);if(!$quantity){throw new Exception('Movement quantity must not be zero.');}if(in_array($doc->doc_type,[ShopStoreDocMove::DOCTYPE_SALE,ShopStoreDocMove::DOCTYPE_WRITEOFF],true)){$quantity=-abs($quantity);}elseif(in_array($doc->doc_type,[ShopStoreDocMove::DOCTYPE_RETURN,ShopStoreDocMove::DOCTYPE_POSTING],true)){$quantity=abs($quantity);}if($new){$m->shop_store_doc_move_id=$doc->id;}$m->shop_store_product_id=$position->id;$m->product_name=(string)($source['product_name']??$position->productName);$m->quantity=$quantity;if(array_key_exists('price',$source)){$m->price=(float)$source['price'];}elseif($new){$m->price=(float)$position->selling_price;}$m->is_active=0; }
    public function documentData(ShopStoreDocMove $m,bool $details=false): array { $d=$this->recordData($m);$d['doc_type_text']=$m->docTypeAsText;if($details){$d['items']=array_map([$this,'recordData'],$m->shopStoreProductMoves);$d['store']=$m->shopStore?$this->recordData($m->shopStore):null;$d['order']=$m->shopOrder?$this->recordData($m->shopOrder):null;}return $d; }
}
